create sequence student_seq start with 1 increment by 50;
create table course (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table course_signed (course_id bigint not null, student_id bigint not null);
create table student (id bigint not null, name varchar(255) not null, primary key (id));
alter table if exists course_signed add constraint FK16l6emv2wl432n92vwxtwqfoa foreign key (course_id) references course;
alter table if exists course_signed add constraint FKk4lp7ovjsp7egrvqsevmygb94 foreign key (student_id) references student;

    create sequence student_seq start with 1 increment by 50;

    create table course (
        id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (id)
    );

    create table course_signed (
        course_id bigint not null,
        student_id bigint not null
    );

    create table student (
        id bigint not null,
        name varchar(255) not null,
        primary key (id)
    );

    alter table if exists course_signed 
       add constraint FK16l6emv2wl432n92vwxtwqfoa 
       foreign key (course_id) 
       references course;

    alter table if exists course_signed 
       add constraint FKk4lp7ovjsp7egrvqsevmygb94 
       foreign key (student_id) 
       references student;

    create sequence student_seq start with 1 increment by 50;

    create table course (
        id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (id)
    );

    create table course_signed (
        course_id bigint not null,
        student_id bigint not null
    );

    create table student (
        id bigint not null,
        name varchar(255) not null,
        primary key (id)
    );

    alter table if exists course_signed 
       add constraint FK16l6emv2wl432n92vwxtwqfoa 
       foreign key (course_id) 
       references course;

    alter table if exists course_signed 
       add constraint FKk4lp7ovjsp7egrvqsevmygb94 
       foreign key (student_id) 
       references student;

    create sequence student_seq start with 1 increment by 50;

    create table course (
        id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (id)
    );

    create table course_signed (
        course_id bigint not null,
        student_id bigint not null
    );

    create table student (
        id bigint not null,
        name varchar(255) not null,
        primary key (id)
    );

    alter table if exists course_signed 
       add constraint FK16l6emv2wl432n92vwxtwqfoa 
       foreign key (course_id) 
       references course;

    alter table if exists course_signed 
       add constraint FKk4lp7ovjsp7egrvqsevmygb94 
       foreign key (student_id) 
       references student;
create sequence student_seq start with 1 increment by 50;
create table course (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table course_signed (course_id bigint not null, student_id bigint not null);
create table student (id bigint not null, name varchar(255) not null, primary key (id));
alter table if exists course_signed add constraint FK16l6emv2wl432n92vwxtwqfoa foreign key (course_id) references course;
alter table if exists course_signed add constraint FKk4lp7ovjsp7egrvqsevmygb94 foreign key (student_id) references student;
create sequence student_seq start with 1 increment by 50;
create table course (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table course_signed (course_id bigint not null, student_id bigint not null);
create table student (id bigint not null, name varchar(255) not null, primary key (id));
alter table if exists course_signed add constraint FK16l6emv2wl432n92vwxtwqfoa foreign key (course_id) references course;
alter table if exists course_signed add constraint FKk4lp7ovjsp7egrvqsevmygb94 foreign key (student_id) references student;
create sequence student_seq start with 1 increment by 50;
create table course (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table course_signed (course_id bigint not null, student_id bigint not null);
create table student (id bigint not null, name varchar(255) not null, primary key (id));
alter table if exists course_signed add constraint FK16l6emv2wl432n92vwxtwqfoa foreign key (course_id) references course;
alter table if exists course_signed add constraint FKk4lp7ovjsp7egrvqsevmygb94 foreign key (student_id) references student;
create sequence student_seq start with 1 increment by 50;
create table course (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table course_signed (course_id bigint not null, student_id bigint not null);
create table student (id bigint not null, name varchar(255) not null, primary key (id));
alter table if exists course_signed add constraint FK16l6emv2wl432n92vwxtwqfoa foreign key (course_id) references course;
alter table if exists course_signed add constraint FKk4lp7ovjsp7egrvqsevmygb94 foreign key (student_id) references student;
create sequence student_seq start with 1 increment by 50;
create table course (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table course_signed (course_id bigint not null, student_id bigint not null);
create table student (id bigint not null, name varchar(255) not null, primary key (id));
alter table if exists course_signed add constraint FK16l6emv2wl432n92vwxtwqfoa foreign key (course_id) references course;
alter table if exists course_signed add constraint FKk4lp7ovjsp7egrvqsevmygb94 foreign key (student_id) references student;
create sequence student_seq start with 1 increment by 50;
create table course (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table course_signed (course_id bigint not null, student_id bigint not null);
create table student (id bigint not null, name varchar(255) not null, primary key (id));
alter table if exists course_signed add constraint FK16l6emv2wl432n92vwxtwqfoa foreign key (course_id) references course;
alter table if exists course_signed add constraint FKk4lp7ovjsp7egrvqsevmygb94 foreign key (student_id) references student;
create sequence student_seq start with 1 increment by 50;
create table course (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table course_signed (course_id bigint not null, student_id bigint not null);
create table student (id bigint not null, name varchar(255) not null, primary key (id));
alter table if exists course_signed add constraint FK16l6emv2wl432n92vwxtwqfoa foreign key (course_id) references course;
alter table if exists course_signed add constraint FKk4lp7ovjsp7egrvqsevmygb94 foreign key (student_id) references student;
create sequence student_seq start with 1 increment by 50;
create table course (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table course_signed (course_id bigint not null, student_id bigint not null);
create table student (id bigint not null, name varchar(255) not null, primary key (id));
alter table if exists course_signed add constraint FK16l6emv2wl432n92vwxtwqfoa foreign key (course_id) references course;
alter table if exists course_signed add constraint FKk4lp7ovjsp7egrvqsevmygb94 foreign key (student_id) references student;
create sequence student_seq start with 1 increment by 50;
create table course (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table course_signed (course_id bigint not null, student_id bigint not null);
create table student (id bigint not null, name varchar(255) not null, primary key (id));
alter table if exists course_signed add constraint FK16l6emv2wl432n92vwxtwqfoa foreign key (course_id) references course;
alter table if exists course_signed add constraint FKk4lp7ovjsp7egrvqsevmygb94 foreign key (student_id) references student;
create sequence student_seq start with 1 increment by 50;
create table course (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table course_signed (course_id bigint not null, student_id bigint not null);
create table student (id bigint not null, name varchar(255) not null, primary key (id));
alter table if exists course_signed add constraint FK16l6emv2wl432n92vwxtwqfoa foreign key (course_id) references course;
alter table if exists course_signed add constraint FKk4lp7ovjsp7egrvqsevmygb94 foreign key (student_id) references student;
create sequence student_seq start with 1 increment by 50;
create table course (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table course_signed (course_id bigint not null, student_id bigint not null);
create table student (id bigint not null, name varchar(255) not null, primary key (id));
alter table if exists course_signed add constraint FK16l6emv2wl432n92vwxtwqfoa foreign key (course_id) references course;
alter table if exists course_signed add constraint FKk4lp7ovjsp7egrvqsevmygb94 foreign key (student_id) references student;
create sequence student_seq start with 1 increment by 50;
create table course (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table course_signed (course_id bigint not null, student_id bigint not null);
create table student (id bigint not null, name varchar(255) not null, primary key (id));
alter table if exists course_signed add constraint FK16l6emv2wl432n92vwxtwqfoa foreign key (course_id) references course;
alter table if exists course_signed add constraint FKk4lp7ovjsp7egrvqsevmygb94 foreign key (student_id) references student;
