apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-probe
spec:
  selector:
    matchLabels:
      app: cluster-probe
  replicas: 3
  template:
    metadata:
      labels:
        app: cluster-probe
    spec:
      containers:
        - name: cluster-probe
          image: 9909733/9909733:tag_1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
