apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: cluster-probe-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cluster-probe
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70