apiVersion: v1
kind: Service
metadata:
  name: cluster-probe-service
spec:
  ports:
    - protocol: "TCP"
      port: 8080       
      targetPort: 8080  
  type: NodePort        
  selector:
    app: cluster-probe