/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.FileSystemSpecification;
import io.swagger.client.model.TestSpecification;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ControllerApi
 */
@Ignore
public class ControllerApiTest {

    private final ControllerApi api = new ControllerApi();

    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createFilesTest() throws Exception {
        FileSystemSpecification body = null;
        String response = api.createFiles(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void payloadTestTest() throws Exception {
        Map<String, String> body = null;
        Map<String, String> response = api.payloadTest(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void startJobTest() throws Exception {
        TestSpecification body = null;
        String response = api.startJob(body);

        // TODO: test validations
    }
}
