/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Course;
import io.swagger.client.model.Student;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for SchoolControllerApi
 */
@Ignore
public class SchoolControllerApiTest {

    private final SchoolControllerApi api = new SchoolControllerApi();

    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void addCourseTest() throws Exception {
        Course body = null;
        Course response = api.addCourse(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void addCourseForStudentTest() throws Exception {
        Long studentId = null;
        Long courseId = null;
        Student response = api.addCourseForStudent(studentId, courseId);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void addStudentTest() throws Exception {
        Student body = null;
        Student response = api.addStudent(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void clearAllTest() throws Exception {
        String response = api.clearAll();

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAllCoursesTest() throws Exception {
        List<Course> response = api.getAllCourses();

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAllStudentsTest() throws Exception {
        List<Student> response = api.getAllStudents();

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAllStudentsForCourseTest() throws Exception {
        Long courseId = null;
        List<Student> response = api.getAllStudentsForCourse(courseId);

        // TODO: test validations
    }
}
