name: Test PR

on: pull_request

jobs:
  test-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup gradle
        run: mvn --batch-mode --update-snapshots package

      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
